## 异步处理
- 回调函数
```javascript
function fetchData(callBack) {
    setTimeout(function () {
        const data = {name: 'test'}
        callBack(data)
    },1000)
}
fetchData(function (data) {
    console.log(data)
})
```
- Promise
```javascript
const fetchData = new Promise((resolve, reject) => {
    const data = {name: 'test'}
    resolve(data)
})
fetchData.then((data) => {
    console.log(data)
},()=> {})
```
- async/await
```javascript
const fetchData = new Promise((resolve, reject) => {
    const data = {name: 'test'}
    resolve(data)
})
async function main() {
    const data = await fetchData
    console.log(data)
}

main() 

```
异步处理常见场景
 - 网络请求
 - 定时人物
 - 事件绑定
 - 大量数据处理

处理策略

- 回调函数
- Promise
- async/await
- 发布订阅模式
- Generator模式
- promise.all
- 预加载资源（性能优化）
- 事件监听

## 1. 简版Promise
### 1.1 resolve和reject
````javascript
let p1 = new Promise((resolve, reject) => {
    resolve('success')
    reject('fail')
})
console.log('p1', p1)
let p2 = new Promise((resolve, reject) => {
    reject('success')
    resolve('fail')
})
console.log('p2', p2)
let p3 = new Promise((resolve, reject) => {
    throw ('error')
})
console.log('p3', p3)
````
Promise的四个特点：
1. 执行了resolve，Promise状态会变成`fulfilled`
2. 执行了reject，Promise状态会变成`rejected`
3. Promise状态不可逆，第一次成功就会永久为`fulfilled`，第一次失败就永远状态为`rejected`
4. Promise中有throw的话，就相当与执行了reject
#### 1.1.1 实现resolve和reject
1. Promise的初始状态是pending
2. 需要对resole和reject绑定this：resole和reject的this指向永远指向当前的MyPromise实例，防止随着函数执行环境的改变而改变
```javascript
class myPromise {
    constructor(executor) {
        // 初始化值
        this.initValue()
        // 初始化绑定this
        this.initBinding()
        executor( this.resolve, this.reject)
    }
    initValue() {
        this.PromiseState = 'pending'
        this.PromiseResult = null
    }
    initBinding() {
        this.resolve = this.resolve.bind(this)
        this.reject = this.reject.bind(this)
    }
    resolve(value) {
   
        this.PromiseState = 'fulfilled'
        this.PromiseResult = value
    }
    reject(reason) {
        if (this.PromiseState !== 'pending')  return
        this.PromiseState = 'rejected'
        this.PromiseResult = reason
    }
}

```

```javascript
const test1 = new myPromise((resolve, reject) => {
    resolve('success')
})
console.log(test1)

/*
* myPromise {
  PromiseState: 'fulfilled',
  PromiseResult: 'success',
  resolve: [Function: bound resolve],
  reject: [Function: bound reject]
}
* */
const test2 = new myPromise((resolve, reject) => {
    reject('error')
})
console.log(test2)
/*
*myPromise {
  PromiseState: 'rejected',
  PromiseResult: 'error',
  resolve: [Function: bound resolve],
  reject: [Function: bound reject]
}
 */
```

#### 1.1.2 状态不可变
Promise有三种状态:
- pending: 等待中，是初始状态
- fulfilled: 成功
- rejected：失败

状态不为pending，此Promise实例的状态就不可以改变
```javascript
class myPromise {
    constructor(executor) {
        // 初始化值
        this.initValue()
        // 初始化绑定this
        this.initBinding()
        executor( this.resolve, this.reject)
    }
    initValue() {
        this.PromiseState = 'pending'
        this.PromiseResult = null
    }
    initBinding() {
        this.resolve = this.resolve.bind(this)
        this.reject = this.reject.bind(this)
    }
    resolve(value) {
        if (this.PromiseState !== 'pending')  return
        this.PromiseState = 'fulfilled'
        this.PromiseResult = value
    }
    reject(reason) {
        if (this.PromiseState !== 'pending')  return
        this.PromiseState = 'rejected'
        this.PromiseResult = reason
    }
}

```
```javascript
const test3 = new myPromise((resolve, reject) => {
    reject('error')
    resolve('success')
})
console.log(test3)
//myPromise {
// PromiseState: 'fulfilled',
//     PromiseResult: 'success',
//     resolve: [Function: bound resolve],
// reject: [Function: bound reject]
// }
```

#### 1.1.3 throw
Promise中有throw的话，就相当于执行了reject。这就要使用try catch了

```javascript
class myPromise {
    constructor(executor) {
        // 初始化值
        this.initValue()
        // 初始化绑定this
        this.initBinding()
        try {
            executor( this.resolve, this.reject)
        }catch (e) {
            this.reject('error')
        }

    }
    initValue() {
        this.PromiseState = 'pending'
        this.PromiseResult = null
    }
    initBinding() {
        this.resolve = this.resolve.bind(this)
        this.reject = this.reject.bind(this)
    }
    resolve(value) {
        if (this.PromiseState !== 'pending')  return
        this.PromiseState = 'fulfilled'
        this.PromiseResult = value
    }
    reject(reason) {
        if (this.PromiseState !== 'pending')  return
        this.PromiseState = 'rejected'
        this.PromiseResult = reason
    }
}

```
### 1.2 then
```javascript
// 马上输出 ”success“
const p1 = new Promise((resolve, reject) => {
    resolve('success')
}).then(res => console.log(res), err => console.log(err))

// 1秒后输出 ”fail“
const p2 = new Promise((resolve, reject) => {
    setTimeout(() => {
        reject('fail')
    }, 1000)
}).then(res => console.log(res), err => console.log(err))

// 链式调用 输出 200
const p3 = new Promise((resolve, reject) => {
    resolve(100)
}).then(res => 2 * res, err => console.log(err))
  .then(res => console.log(res), err => console.log(err))
```
1. then接受两个回调，一个是成功回调，一个是失败回调
2. 当Promise状态是fulfilled执行成功回调，是rejected执行失败回调
3. 如果resolve/reject在定时器中，定时器结束后在执行then
4. then支持链式调用，下一次then执行受上次then返回值的影响

#### 1.2.1 实现then
```javascript
then(onFulfilled, onRejected) {
      // 接收两个回调 onFulfilled, onRejected
      
      // 参数校验，确保一定是函数
      onFulfilled = typeof onFulfilled === 'function' ? onFulfilled : val => val
      onRejected = typeof onRejected === 'function' ? onRejected : reason => { throw reason }

      if (this.PromiseState === 'fulfilled') {
          // 如果当前为成功状态，执行第一个回调
          onFulfilled(this.PromiseResult)
      } else if (this.PromiseState === 'rejected') {
          // 如果当前为失败状态，执行第二哥回调
          onRejected(this.PromiseResult)
      }

    }
```
```javascript
// 输出 ”success“
const test = new MyPromise((resolve, reject) => {
    resolve('success')
}).then(res => console.log(res), err => console.log(err))
```

#### 1.2.2 定时器
1. 增加队列
2. 判断是否状态为pending，如果是则增加到队列中
3. 定时器结果，执行

#### 1.2.3 链式调用
```javascript
// 链式调用 输出 200
const p3 = new Promise((resolve, reject) => {
  resolve(100)
}).then(res => 2 * res, err => console.log(err))
  .then(res => console.log(res), err => console.log(err))

// 链式调用 输出300
const p4 = new Promise((resolve, reject) => {
  resolve(100)
}).then(res => new Promise((resolve, reject) => resolve(3 * res)), err => console.log(err))
  .then(res => console.log(res), err => console.log(err))
```
1. then本身会返回一个新的promise对象
2. 返回值是Promise对象，返回值是成功，新的promise就是成功
3. 返回值是Promise对象，返回值是失败，新的promise就是失败
4. 返回值不是Promise对象，新promise就是成功，返回值就是当前返回值
#### 1.2.4 执行顺序
then的方法是微任务
```javascript
const p = new Promise((resolve, reject) => {
    resolve(1)
}).then(res => console.log(res), err => console.log(err))

console.log(2)

// 输出顺序是 2 1

```
使用定时器，增加微任务 

setTimeout是宏任务
```javascript
class myPromise {
    constructor(executor) {
        // 初始化值
        this.initValue()
        // 初始化绑定this
        this.initBinding()
        try {
            executor( this.resolve, this.reject)
        }catch (e) {
            this.reject('error')
        }

    }
    initValue() {
        this.PromiseState = 'pending'
        this.PromiseResult = null
        // 保存成功/失败回调
        this.onFulfilledCallbacks = []
        this.onRejectedCallbacks = []
    }
    initBinding() {
        this.resolve = this.resolve.bind(this)
        this.reject = this.reject.bind(this)
    }
    resolve(value) {
        if (this.PromiseState !== 'pending')  return
        this.PromiseState = 'fulfilled'
        this.PromiseResult = value
        // 执行保存的成功回调
        while (this.onFulfilledCallbacks.length) {
            this.onFulfilledCallbacks.shift()(this.PromiseResult)
        }
    }
    reject(reason) {
        if (this.PromiseState !== 'pending')  return
        this.PromiseState = 'rejected'
        this.PromiseResult = reason
        while (this.onRejectedCallbacks.length) {
            this.onRejectedCallbacks.shift()(this.PromiseResult)
        }
    }
    then(onFulfilled, onRejected) {
        onFulfilled = typeof onFulfilled === 'function' ? onFulfilled : val => val
        onRejected = typeof onRejected === 'function' ? onRejected : reason => { throw reason }
        // 链式调用
        var thenPromise = new myPromise((resolve, reject) => {
            const resolvePromise = (cb) => {
                // 使用try catch 捕获异常
                setTimeout(() => {
                    try {
                        console.log(cb)
                        const x = cb(this.PromiseResult)
                        if (x === thenPromise && x)  {
                            throw new Error('不能返回自身....')
                        }
                        if (x  instanceof myPromise)  {
                            x.then(resolve,reject)
                        }else {
                            resolve(x)
                        }

                    } catch (err) {
                        reject(err)
                        throw new Error(err)
                    }
                })
            }
            if (this.PromiseState === 'fulfilled')  {
                // 如果当前是成功，执行第一个回调
                resolvePromise(onFulfilled)
            }else if (this.PromiseState === 'rejected')  {
                // 如果当前是失败，执行第一个回调
                resolvePromise(onRejected)
            }else if (this.PromiseState === 'pending')  {
                this.onFulfilledCallbacks.push(onFulfilled.bind(this))
                this.onRejectedCallbacks.push(onRejected.bind(this))
            }
        })
         return  thenPromise
    }
}
```
```javascript

const test4 = new MyPromise((resolve, reject) => {
    resolve(1)
}).then(res => console.log(res), err => console.log(err))

console.log(2)

// 2,1
```
### 1.3 其他方法
#### 1.3.1 all
1. 接收一个promise数组，
2. 所有都成功，返回成功
3. 如果有一个失败，返回这个失败结果

```javascript
const test1 = new myPromise((resolve, reject) => {
    resolve(100)
})
const test2 = new myPromise((resolve, reject) => {
    resolve(200)
})
myPromise.all([test1, test2,300]).then(result => {console.log(result)})
```

#### 1.3.2 race
1. 接收一个Promise数组，数组中如有非Promise项，则此项当做成功；
2. 哪个Promise最快得到结果，就返回那个结果，无论成功失败；
#### 1.3.3 allSettled
1. 接收一个Promise数组，数组中如有非Promise项，则此项当做成功；
2. 把每一个Promise的结果，集合成数组后返回；
#### 1.3.4 any
与all相反
1. 接收一个Promise数组，数组中如有非Promise项，则此项当做成功；
2. 如果有一个Promise成功，则返回这个成功结果；
3. 如果所有Promise都失败，则报错；
### 1.4 随堂作业
## 2. Promise A+规范

### 2.1 术语
### 2.2 要求
#### 2.2.1 promise状态
#### 2.2.2 then
#### 2.2.3 Promise Resolution Procedure
## 3. async/await
### 3.1 介绍
用同步方法，执行异步操作

```javascript
function request(num) {
    return new Promise(function (resolve, reject) { 
        setTimeout(()=> {
            resolve(numb*100)
        },1000)
    })
}
request(10).then(res=> {
    console.log(res)
    request(2).then(res1=> {
        console.log(res1)
    })
})

request(10).then(res=> {
    console.log(res)
    request(res).then(res1=> {
        console.log(res1)
    })
})

```
```javascript
// 使用saync/await替换
async function fn () {
    const res1 = await request(5)
    const res2 = await request(res1)
    console.log(res2)
}
fn()
```

#### 3.1.1 总结
1. await只能在async函数中使用，不然会报错；
2. async函数返回的是一个Promise对象，有无值看有无return值；
3. await后面最好是接Promise，虽然接其他值也能达到排队效；
4. async/await作用是用同步方式，执行异步操作
#### 3.1.2 语法糖
Q：async/await是一种语法糖，那么什么是语法糖呢？
A：语法糖是简化代码的一种方式，用其他方式也能达到同样的效果，但写法可能没有这么便利。
ES6的class也是语法糖，因为其实用普通function也能实现同样效果
回归正题，async/await是一种语法糖，用到的是ES6里的迭代函数——generator函数
## 4. generator
### 4.1 介绍
generator函数跟普通函数在写法上的区别就是，多了一个星号*，并且只有在generator函数中才能使用yield，而yield相当于generator函数执行的中途暂停点，比如下方有3个暂停点。而怎么才能暂停后继续走呢？那就得使用到next方法，next方法执行后会返回一个对象，对象中有value 和 done两个属性
- value：暂停点后面接的值，也就是yield后面接的值；
- done：是否generator函数已走完，没走完为false，走完为true；
```javascript
function* gen() {
  yield 1
  yield 2
  yield 3
    return 4
}
const g = gen()
console.log(g.next()) // { value: 1, done: false }
console.log(g.next()) // { value: 2, done: false }
console.log(g.next()) // { value: 3, done: false }
console.log(g.next()) // { value: undefined, done: true }
```
#### 4.1.1 yield后接函数
yield 后接函数，到达对应的暂停点，就会立即执行此函数，摒弃该函数执行返回值，会被当成此暂停点对象的value
````javascript
function fn(num) {
    console.log(num)
    return num
}
function* gen() {
    yield fn(1)
    yield fn(2)
    return 3
}
const g = gen()

console.log(g.next())
console.log(g.next())
console.log(g.next())

````


#### 4.1.2 yield后接promise
````javascript
function fn(num) {
    return new Promise(function (resolve, reject) { 
     
        setTimeout(() => {
            resolve(num) 
        },1000)
    })
}
function* gen() {
    yield fn(1)
    yield fn(2)
    return 3
}
const g = gen()

console.log(g.next().value.then(res => {console.log(res)}))
console.log(g.next().value.then(res => {console.log(res)}))
console.log(g.next())

````


```javascript
function* gen() {
    yield fn(1)
    yield fn(2)
    return 3
}
const g = gen()
const next1 = g.next()
next1.value.then(res1 => {
  console.log(next1) // 1秒后输出 { value: Promise { 1 }, done: false }
  console.log(res1) // 1秒后输出 1

  const next2 = g.next()
  next2.value.then(res2 => {
    console.log(next2) // 2秒后输出 { value: Promise { 2 }, done: false }
    console.log(res2) // 2秒后输出 2
    console.log(g.next()) // 2秒后输出 { value: 3, done: true }
  })
})
```

#### 4.1.3 next函数传参



#### 4.1.4 Promise&next传参
### 4.2 实现all/await
#### 4.2.1 返回值promise
#### 4.2.2 结合上述代码
#### 4.2.3 结合多个await方法
#### 4.2.4 测试结果